# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb
orbs:
  # Declare a dependency on the sofy-orb
  sofy: sofy-ai/sofy@1.1.1
# Orchestrate or schedule a set of jobs
jobs:
  build_job:
     docker:
        - image: circleci/android:api-29
     steps:
          # Add steps to build your app here. After your app building process is complete, add the following step with your 'Sofy Subscription Key' &
          # 'Build Path' to upload the build directly to SOFY AI
          - sofy/connect_sofy:
               subscription_key: "80b30c4e-c920-40a7-9682-6ad2e779a67f"
               build_path: "/home/circleci/project/app.apk"
workflows:
  # Name the workflow "appbuild"
  appbuild:
     # Run the appbuild job in its own container
     jobs:
     - build_job
