on: [push]
jobs:
  Uploading-job:  
    name: 'Upload build on Sofy3.0'
    runs-on: ubuntu-latest
    steps:
      - name: 'checkout'
        uses: actions/checkout@v2
      - name: 'Upload build' 
        env:
          build_path: 'Byte.ipa'
          subscription_key: 80b30c4e-c920-40a7-9682-6ad2e779a67f
        uses: 'SOFYAIOFFICIAL/sofy-upload-github-actions@main'
