on: [push]
jobs:
  Uploading-job:
    name: 'Upload build on Sofy3.0'
    runs-on: ubuntu-latest
    steps:
      - name: 'checkout'
        uses: actions/checkout@v2
      - name: 'Upload build'
        uses: 'SOFYDEVELOPER/sofy-app-upload-github-action@main'
        env:
          build_path: Byte.ipa
          subscription_key: FEBF2165-8521-4467-9339-8895C8A48C12
          application_guid: 72AC706F-A924-4C55-97DE-253C5E60FFC0
          certificate_name: 'abc abc'
