on: [push]
jobs:
  Uploading-job:  
    name: 'Upload build on Sofy3.0'
    runs-on: ubuntu-latest
    steps:
      - name: 'checkout'
        uses: actions/checkout@v2
      - name: 'Upload build' 
        env:
          build_path: 'Byte.ipa'
          subscription_key: a67b358c-b3bb-4737-bee3-db491e6d2bcc
        uses: 'SOFYAIOFFICIAL/sofy-upload-github-actions@main'
