on: [push]
jobs:
  Uploading-job:
    name: 'Upload build on Sofy3.0'
    runs-on: ubuntu-latest
    steps:
      - name: 'checkout'
        uses: actions/checkout@v2
      - name: 'Set certificate name'
        run: |
          echo "CERTIFICATE_NAME=Trueblue Srl" >> $GITHUB_ENV
      - name: 'Upload build'
        run: |
          CERTIFICATE_NAME=$(cat $GITHUB_ENV | grep CERTIFICATE_NAME | cut -d '=' -f2)
          ./upload-script.sh --certificate "$CERTIFICATE_NAME"
